on:
  push

name: Test comment

jobs:
  test-comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create new issue
      id: create
      uses: atlassian/gajira-create@master

    - name: Comment on issue
      uses: ./
      with:
        issue: ${{ steps.create.outputs.issue }}
        comment: Test comment